/**
 * generate-workforce.ts
 *
 * Reads businesses/*.yaml and generates the businesses + teamInstances
 * portions of workforce.ts. Roles, team templates, executives, skills,
 * and helpers stay hand-written.
 *
 * Usage: npx tsx scripts/generate-workforce.ts
 * Run before `next build` to keep dashboard in sync with YAML configs.
 */
import * as fs from "fs";
import * as path from "path";
import * as yaml from "js-yaml";

const BUSINESSES_DIR = path.join(__dirname, "../../businesses");
const OUTPUT_FILE = path.join(__dirname, "../src/data/generated-workforce.ts");

interface BizYaml {
  id: string;
  name: string;
  status: string;
  website?: string;
  description?: string;
  org?: {
    director?: string;
    director_name?: string;
    reportsTo?: string;
    github?: string;
    path?: string;
  };
  deploy?: {
    platform?: string;
  };
  teams?: Array<{
    template: string;
    instance_id?: string;
    runs_on?: string;
    schedule?: string;
    status?: string;
  }>;
}

function loadBusinessYamls(): BizYaml[] {
  const files = fs
    .readdirSync(BUSINESSES_DIR)
    .filter((f) => f.endsWith(".yaml") && !f.startsWith("_"));

  return files.map((f) => {
    const raw = fs.readFileSync(path.join(BUSINESSES_DIR, f), "utf8");
    return yaml.load(raw) as BizYaml;
  });
}

function generateBusinesses(bizList: BizYaml[]): string {
  const entries = bizList.map((biz) => {
    const fields = [
      `    id: ${JSON.stringify(biz.id)}`,
      `    name: ${JSON.stringify(biz.name)}`,
      `    status: ${JSON.stringify(biz.status)} as ProjectStatus`,
      `    path: ${JSON.stringify(biz.org?.path || "")}`,
    ];

    if (biz.website) fields.push(`    website: ${JSON.stringify(biz.website.replace("https://", ""))}`);
    if (biz.deploy?.platform) fields.push(`    deploy: ${JSON.stringify(biz.deploy.platform)}`);
    if (biz.org?.github) fields.push(`    github: ${JSON.stringify(biz.org.github)}`);
    if (biz.description) fields.push(`    description: ${JSON.stringify(biz.description)}`);
    fields.push(`    directorId: ${JSON.stringify(biz.org?.director || `dir-${biz.id}`)}`);

    return `  {\n${fields.join(",\n")},\n  }`;
  });

  return `export const generatedBusinesses: Business[] = [\n${entries.join(",\n")}\n];`;
}

function generateTeamInstances(bizList: BizYaml[]): string {
  const entries: string[] = [];

  for (const biz of bizList) {
    if (!biz.teams || biz.teams.length === 0) continue;

    for (const team of biz.teams) {
      const instanceId = team.instance_id || `${biz.id}-${team.template.replace(/-team$/, "")}`;
      const fields = [
        `    id: ${JSON.stringify(instanceId)}`,
        `    templateId: ${JSON.stringify(team.template)}`,
        `    businessId: ${JSON.stringify(biz.id)}`,
        `    status: ${JSON.stringify(team.status || "idle")} as AgentStatus`,
        `    runsOn: ${JSON.stringify(team.runs_on || "not deployed")}`,
      ];

      if (team.schedule) fields.push(`    schedule: ${JSON.stringify(team.schedule)}`);

      entries.push(`  {\n${fields.join(",\n")},\n  }`);
    }
  }

  return `export const generatedTeamInstances: TeamInstance[] = [\n${entries.join(",\n")}\n];`;
}

function main() {
  const bizList = loadBusinessYamls();
  console.log(`Loaded ${bizList.length} business YAML files`);

  const output = `// AUTO-GENERATED — do not edit by hand.
// Source: businesses/*.yaml
// Generated by: scripts/generate-workforce.ts
// Run: npx tsx scripts/generate-workforce.ts

import type { Business, TeamInstance, ProjectStatus, AgentStatus } from "./workforce";

${generateBusinesses(bizList)}

${generateTeamInstances(bizList)}
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`Wrote ${OUTPUT_FILE}`);
  console.log(`  ${bizList.length} businesses`);
  console.log(`  ${bizList.reduce((sum, b) => sum + (b.teams?.length || 0), 0)} team instances`);
}

main();
