/**
 * generate-skills.ts
 *
 * Reads agent-command-center/skills/<name>/SKILL.md and generates a TypeScript
 * module with skill metadata for the dashboard. Parses YAML frontmatter to
 * extract name, version, description, triggers, allowed-tools.
 *
 * Cross-references with businesses/*.yaml to determine where each skill runs
 * (VPS vs GitHub Actions vs manual) by matching skill names to teams[].template.
 *
 * Usage: npx tsx scripts/generate-skills.ts
 * Run before `next build`.
 */
import * as fs from "fs";
import * as path from "path";
import * as yaml from "js-yaml";

const SKILLS_DIR = path.join(__dirname, "../../skills");
const BUSINESSES_DIR = path.join(__dirname, "../../businesses");
const OUTPUT_FILE = path.join(__dirname, "../src/data/generated-skills.ts");

interface SkillFrontmatter {
  name?: string;
  version?: string;
  description?: string;
  invocation?: string;
  triggers?: string[];
  "allowed-tools"?: string[];
}

interface BizYaml {
  id: string;
  name: string;
  teams?: Array<{
    template: string;
    instance_id?: string;
    runs_on?: string;
    schedule?: string;
    cron?: string;
    status?: string;
  }>;
}

interface SkillDeployment {
  business_id: string;
  business_name: string;
  runs_on: string;
  schedule: string;
  cron?: string;
  status: string;
}

interface GeneratedSkill {
  id: string;
  name: string;
  version: string;
  description: string;
  invocation: string;
  triggers: string[];
  allowed_tools: string[];
  deployments: SkillDeployment[];
}

function parseFrontmatter(content: string): SkillFrontmatter | null {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return null;
  try {
    return yaml.load(match[1]) as SkillFrontmatter;
  } catch {
    return null;
  }
}

function loadBusinesses(): BizYaml[] {
  if (!fs.existsSync(BUSINESSES_DIR)) return [];
  return fs
    .readdirSync(BUSINESSES_DIR)
    .filter((f) => f.endsWith(".yaml") && !f.startsWith("_"))
    .map((f) => {
      try {
        return yaml.load(fs.readFileSync(path.join(BUSINESSES_DIR, f), "utf-8")) as BizYaml;
      } catch {
        return null;
      }
    })
    .filter((b): b is BizYaml => b !== null && !!b.id);
}

function findDeployments(skillId: string, businesses: BizYaml[]): SkillDeployment[] {
  const out: SkillDeployment[] = [];
  for (const biz of businesses) {
    if (!biz.teams) continue;
    for (const team of biz.teams) {
      // Match skill to team template — templates are like "seo-content-team" or "podcast-pipeline-team"
      // Skill ID maps when team.template starts with skill ID OR contains it
      const tmplLower = (team.template || "").toLowerCase();
      const skillLower = skillId.toLowerCase();
      const matches =
        tmplLower === skillLower ||
        tmplLower === `${skillLower}-team` ||
        tmplLower.startsWith(`${skillLower}-`) ||
        tmplLower.includes(skillLower.replace(/-/g, ""));
      if (!matches) continue;
      out.push({
        business_id: biz.id,
        business_name: biz.name,
        runs_on: team.runs_on || "unknown",
        schedule: team.schedule || "—",
        cron: team.cron,
        status: team.status || "unknown",
      });
    }
  }
  return out;
}

function main() {
  const businesses = loadBusinesses();
  const skillDirs = fs
    .readdirSync(SKILLS_DIR)
    .filter((d) => fs.statSync(path.join(SKILLS_DIR, d)).isDirectory())
    .sort();

  const skills: GeneratedSkill[] = [];
  for (const dir of skillDirs) {
    const skillPath = path.join(SKILLS_DIR, dir, "SKILL.md");
    if (!fs.existsSync(skillPath)) continue;
    const content = fs.readFileSync(skillPath, "utf-8");
    const fm = parseFrontmatter(content);
    if (!fm) continue;
    skills.push({
      id: fm.name || dir,
      name: fm.name || dir,
      version: fm.version || "0.0.0",
      description: fm.description || "",
      invocation: fm.invocation || `/${dir}`,
      triggers: fm.triggers || [],
      allowed_tools: fm["allowed-tools"] || [],
      deployments: findDeployments(dir, businesses),
    });
  }

  const ts = `// AUTO-GENERATED by scripts/generate-skills.ts — do not edit
// Source: agent-command-center/skills/<name>/SKILL.md frontmatter
// Cross-referenced with businesses/<id>.yaml teams[] for deployment info

export interface SkillDeployment {
  business_id: string;
  business_name: string;
  runs_on: string;
  schedule: string;
  cron?: string;
  status: string;
}

export interface GeneratedSkill {
  id: string;
  name: string;
  version: string;
  description: string;
  invocation: string;
  triggers: string[];
  allowed_tools: string[];
  deployments: SkillDeployment[];
}

export const generatedSkills: GeneratedSkill[] = ${JSON.stringify(skills, null, 2)};

export const skillsLastGenerated = "${new Date().toISOString()}";
`;

  fs.writeFileSync(OUTPUT_FILE, ts);
  console.log(`✓ Generated ${skills.length} skills to ${OUTPUT_FILE}`);
  for (const s of skills) {
    console.log(`  ${s.id}  →  ${s.deployments.length} deployment(s)`);
  }
}

main();
