// AUTO-GENERATED — do not edit by hand.
// Source: businesses/*.yaml
// Generated by: scripts/generate-workforce.ts
// Run: npx tsx scripts/generate-workforce.ts

import type { Business, TeamInstance, ProjectStatus, AgentStatus } from "./workforce";

export const generatedBusinesses: Business[] = [
  {
    id: "bass-forecast",
    name: "Bass Forecast",
    status: "building" as ProjectStatus,
    path: "~/Projects/bass-forecast/",
    description: "AI automation and ecosystem build for Bass Forecast. 90-day retainer with Landon Bloomer.",
    directorId: "dir-bass-forecast",
  },
  {
    id: "globalhighlevel",
    name: "GlobalHighLevel.com",
    status: "live" as ProjectStatus,
    path: "~/Developer/projects/marketing/podcast-pipeline/",
    website: "globalhighlevel.com",
    deploy: "Netlify",
    github: "RecoveryBiometrics/content-autopilot",
    description: "Affiliate content site — podcast, blog, SEO. 1,565 articles, 20 episodes/day.",
    directorId: "dir-ghl",
  },
  {
    id: "hatch",
    name: "Hatch Investments",
    status: "not-running" as ProjectStatus,
    path: "~/Projects/hatch-investments/",
    website: "om-builder.onrender.com",
    deploy: "Render",
    github: "RecoveryBiometrics/hatch-investments",
    description: "AI operations platform for real estate syndicators. OM Builder works locally, needs deploy to Cloudflare.",
    directorId: "dir-hatch",
  },
  {
    id: "mailer",
    name: "Mailer Dashboard",
    status: "building" as ProjectStatus,
    path: "~/Developer/projects/marketing/mailer-dashboard/",
    description: "Email campaign management tool. Next.js 14 + Claude AI. In development.",
    directorId: "dir-mailer",
  },
  {
    id: "recovery",
    name: "Recovery Biometrics",
    status: "paused" as ProjectStatus,
    path: "~/Projects/recovery-biometrics/",
    description: "Recovery-focused biometrics app. Paused until SafeBath and Hatch are stable.",
    directorId: "dir-recovery",
  },
  {
    id: "reiamplifi",
    name: "REI Amplifi",
    status: "live" as ProjectStatus,
    path: "~/Projects/reiamplifi/",
    deploy: "GHL",
    description: "Parent agency. 3.5 years on GHL. No custom AI agents — uses GHL built-in automations.",
    directorId: "dir-reiamplifi",
  },
  {
    id: "safebath",
    name: "Safe Bath Grab Bars",
    status: "live" as ProjectStatus,
    path: "~/Developer/projects/safebath/",
    website: "safebathgrabbar.com",
    deploy: "Vercel",
    github: "RecoveryBiometrics/safebath-website",
    description: "Local service business — grab bar installation, bathroom safety. 5 states, 1,427 pages, 366 directory listings.",
    directorId: "dir-safebath",
  }
];

export const generatedTeamInstances: TeamInstance[] = [
  {
    id: "ghl-production",
    templateId: "content-production-team",
    businessId: "globalhighlevel",
    status: "active" as AgentStatus,
    runsOn: "IONOS VPS ($2/mo)",
    schedule: "24/7 — 25-hour cycles, 20 episodes/day",
  },
  {
    id: "ghl-seo-optimizer",
    templateId: "seo-optimizer-team",
    businessId: "globalhighlevel",
    status: "scheduled" as AgentStatus,
    runsOn: "IONOS VPS (inside podcast scheduler)",
    schedule: "Weekly (7-day gate inside scheduler)",
  },
  {
    id: "ghl-analytics",
    templateId: "analytics-team",
    businessId: "globalhighlevel",
    status: "scheduled" as AgentStatus,
    runsOn: "GitHub Actions",
    schedule: "Weekly, Mondays 8:00 AM ET",
  },
  {
    id: "hatch-om",
    templateId: "om-builder-team",
    businessId: "hatch",
    status: "idle" as AgentStatus,
    runsOn: "Render (needs migration to Cloudflare)",
    schedule: "On demand — web UI",
  },
  {
    id: "sb-seo",
    templateId: "seo-content-team",
    businessId: "safebath",
    status: "scheduled" as AgentStatus,
    runsOn: "GitHub Actions",
    schedule: "Daily, 6:00 AM ET",
  },
  {
    id: "sb-directory",
    templateId: "directory-team",
    businessId: "safebath",
    status: "scheduled" as AgentStatus,
    runsOn: "GitHub Actions",
    schedule: "Daily, 6:00 AM ET",
  },
  {
    id: "sb-reporting",
    templateId: "seo-reporting-team",
    businessId: "safebath",
    status: "scheduled" as AgentStatus,
    runsOn: "GitHub Actions",
    schedule: "Weekly, Tuesdays 9:07 AM ET",
  },
  {
    id: "sb-sales",
    templateId: "sales-team",
    businessId: "safebath",
    status: "active" as AgentStatus,
    runsOn: "GHL Conversation AI + Vercel",
    schedule: "Always on — responds to inbound claims",
  },
  {
    id: "sb-operations",
    templateId: "operations-team",
    businessId: "safebath",
    status: "scheduled" as AgentStatus,
    runsOn: "GitHub Actions",
    schedule: "Daily, 6:00 AM ET (report) + on-demand (doctor)",
  },
  {
    id: "sb-analytics",
    templateId: "analytics-team",
    businessId: "safebath",
    status: "scheduled" as AgentStatus,
    runsOn: "GitHub Actions",
    schedule: "Weekly, Mondays 8:00 AM ET",
  }
];
