// AUTO-GENERATED by scripts/generate-skills.ts — do not edit
// Source: agent-command-center/skills/<name>/SKILL.md frontmatter
// Cross-referenced with businesses/<id>.yaml teams[] for deployment info

export interface SkillDeployment {
  business_id: string;
  business_name: string;
  runs_on: string;
  schedule: string;
  cron?: string;
  status: string;
}

export interface GeneratedSkill {
  id: string;
  name: string;
  version: string;
  description: string;
  invocation: string;
  triggers: string[];
  allowed_tools: string[];
  deployments: SkillDeployment[];
}

export const generatedSkills: GeneratedSkill[] = [
  {
    "id": "Analytics Team",
    "name": "Analytics Team",
    "version": "0.0.0",
    "description": "Analyze GA4 data for any business, surface insights, make recommendations, and dispatch instructions to other pipelines (SEO content, podcast, directory). The brain of the system.",
    "invocation": "/analytics-team",
    "triggers": [],
    "allowed_tools": [],
    "deployments": [
      {
        "business_id": "globalhighlevel",
        "business_name": "GlobalHighLevel.com",
        "runs_on": "GitHub Actions",
        "schedule": "Weekly, Mondays 8:00 AM ET",
        "cron": "0 12 * * 1",
        "status": "scheduled"
      },
      {
        "business_id": "safebath",
        "business_name": "Safe Bath Grab Bars",
        "runs_on": "GitHub Actions",
        "schedule": "Weekly, Mondays 8:00 AM ET",
        "cron": "0 12 * * 1",
        "status": "scheduled"
      }
    ]
  },
  {
    "id": "content-builder",
    "name": "content-builder",
    "version": "0.0.0",
    "description": "Build content from SEO TODOs — reads gaps/opportunities from Sheet, researches, writes, fact-checks, interlinks, and deploys.",
    "invocation": "/content-builder",
    "triggers": [],
    "allowed_tools": [],
    "deployments": [
      {
        "business_id": "power-to-the-people",
        "business_name": "Power to the People",
        "runs_on": "GitHub Actions",
        "schedule": "Weekly, Wed 10:00 AM ET",
        "status": "pending_deploy"
      },
      {
        "business_id": "safebath",
        "business_name": "Safe Bath Grab Bars",
        "runs_on": "GitHub Actions",
        "schedule": "Weekly, Wednesdays 6:00 AM ET",
        "cron": "0 10 * * 3",
        "status": "scheduled"
      }
    ]
  },
  {
    "id": "content-localizer",
    "name": "content-localizer",
    "version": "0.0.0",
    "description": "Classify language + topic, localize CTAs/pricing/currency, and place blog post JSONs correctly. Called by any content pipeline.",
    "invocation": "/localize",
    "triggers": [],
    "allowed_tools": [],
    "deployments": []
  },
  {
    "id": "Deploy Team",
    "name": "Deploy Team",
    "version": "0.0.0",
    "description": "Deploy a team template (SEO Content, Directory, Podcast, OM Builder) to a business. Reads config from the business YAML, sets up execution, generates workflows.",
    "invocation": "/deploy-team",
    "triggers": [],
    "allowed_tools": [],
    "deployments": []
  },
  {
    "id": "fix-page-snippet",
    "name": "fix-page-snippet",
    "version": "1.0.0",
    "description": "Rewrites one page's title + meta description together to lift CTR, then measures if it worked. Multi-step: reads current snippet + article opening, researches live SERP, finds intent/specificity gap, drafts 3 title + 3 meta variants, picks winner, ships to post JSON + cooldown lock + Google Sheet SEO Changelog. Has --audit mode that evaluates past rewrites after their 28-day window and auto-rolls back losers. Self-improving: appends proven lever rules back into this file after 10+ measured rewrites.",
    "invocation": "/fix-page-snippet",
    "triggers": [
      "fix page title",
      "rewrite meta",
      "rewrite title and description",
      "improve page CTR",
      "fix snippet",
      "audit snippet rewrites",
      "did the rewrites work"
    ],
    "allowed_tools": [
      "Bash",
      "Read",
      "Write",
      "Edit",
      "mcp__google-workspace__read_sheet_values",
      "mcp__google-workspace__modify_sheet_values"
    ],
    "deployments": []
  },
  {
    "id": "indexing-api",
    "name": "indexing-api",
    "version": "1.0.0",
    "description": "Pings Google Indexing API on new/updated URLs to force same-day discovery. Use when shipping hub pages, verticals, or any URL that can't wait 3-7 days for Google's sitemap re-fetch cycle.",
    "invocation": "/indexing-api",
    "triggers": [
      "ping google indexing",
      "force google to crawl",
      "submit urls to google",
      "request indexing api",
      "google discovery",
      "new url hasn't been crawled",
      "url is unknown to google"
    ],
    "allowed_tools": [
      "Bash",
      "Read",
      "Write",
      "Edit"
    ],
    "deployments": []
  },
  {
    "id": "interlinking",
    "name": "interlinking",
    "version": "0.0.0",
    "description": "Build and maintain internal links across all SafeBath pages — link graph, city neighbors, article relatedLinks, link health audit.",
    "invocation": "/interlinking",
    "triggers": [],
    "allowed_tools": [],
    "deployments": [
      {
        "business_id": "power-to-the-people",
        "business_name": "Power to the People",
        "runs_on": "GitHub Actions",
        "schedule": "Weekly, Sun 11:00 PM ET",
        "status": "pending_deploy"
      }
    ]
  },
  {
    "id": "New Project",
    "name": "New Project",
    "version": "0.0.0",
    "description": "Start a new business project with standard structure — YAML config, CLAUDE.md, git repo, terminal shortcut. Every project starts clean and organized.",
    "invocation": "/new-project",
    "triggers": [],
    "allowed_tools": [],
    "deployments": []
  },
  {
    "id": "OM Builder",
    "name": "OM Builder",
    "version": "0.0.0",
    "description": "Run, audit, or improve the Hatch Investments OM Builder — AI-powered Offering Memorandum generator for commercial real estate. Generates 30-50 page investor-grade PDFs in 43 seconds.",
    "invocation": "/om-builder",
    "triggers": [],
    "allowed_tools": [],
    "deployments": [
      {
        "business_id": "hatch",
        "business_name": "Hatch Investments",
        "runs_on": "Render (needs migration to Cloudflare)",
        "schedule": "On demand — web UI",
        "status": "idle"
      }
    ]
  },
  {
    "id": "Org Status + CEO Briefing",
    "name": "Org Status + CEO Briefing",
    "version": "0.0.0",
    "description": "Quick status check across all businesses, teams, and agents. Also serves as the CEO daily briefing when posted to Slack.",
    "invocation": "/org-status",
    "triggers": [],
    "allowed_tools": [],
    "deployments": []
  },
  {
    "id": "Pipeline Doctor",
    "name": "Pipeline Doctor",
    "version": "0.0.0",
    "description": "Analyze the latest pipeline run, diagnose what went wrong, fix it, and push. Works on GitHub Actions pipelines and IONOS VPS (systemd) pipelines.",
    "invocation": "/pipeline-doctor",
    "triggers": [],
    "allowed_tools": [],
    "deployments": []
  },
  {
    "id": "Podcast Pipeline",
    "name": "Podcast Pipeline",
    "version": "0.0.0",
    "description": "Run, audit, or deploy the podcast + blog production pipeline for any business. Covers content discovery, audio generation, SEO metadata, transcription, publishing, multi-language blog writing, SEO optimization, and analytics.",
    "invocation": "/podcast-pipeline",
    "triggers": [],
    "allowed_tools": [],
    "deployments": []
  },
  {
    "id": "reporting",
    "name": "reporting",
    "version": "0.0.0",
    "description": "Weekly reports, error alerts, and CEO digests for any business. ICM-structured with staged context loading.",
    "invocation": "/report",
    "triggers": [],
    "allowed_tools": [],
    "deployments": [
      {
        "business_id": "safebath",
        "business_name": "Safe Bath Grab Bars",
        "runs_on": "GitHub Actions",
        "schedule": "Weekly, Tuesdays 9:07 AM ET",
        "cron": "7 13 * * 2",
        "status": "scheduled"
      }
    ]
  },
  {
    "id": "SEO Content Pipeline",
    "name": "SEO Content Pipeline",
    "version": "0.0.0",
    "description": "Run, audit, or deploy the daily SEO content pipeline for any business. Covers event scraping, article writing, fact checking, SEO auditing, business discovery, directory management, and weekly SEO reporting.",
    "invocation": "/seo-content-pipeline",
    "triggers": [],
    "allowed_tools": [],
    "deployments": []
  },
  {
    "id": "social-content",
    "name": "social-content",
    "version": "0.0.0",
    "description": "Generate social media posts from ops activity. ICM-structured with staged context loading.",
    "invocation": "/social",
    "triggers": [],
    "allowed_tools": [],
    "deployments": []
  },
  {
    "id": "TODO Agent",
    "name": "TODO Agent",
    "version": "0.0.0",
    "description": "Read Active TODOs from a business's Google Sheet, execute agent-handleable items (SEO optimization, new pages, drop investigation, analytics dispatch), update status, and post summary to Slack.",
    "invocation": "/todo-agent",
    "triggers": [],
    "allowed_tools": [],
    "deployments": []
  },
  {
    "id": "topic-sourcer",
    "name": "topic-sourcer",
    "version": "0.0.0",
    "description": "Source blog topics from 3 tiers (GHL docs, GSC gaps, market verticals) for any language. Called before blog scripts run.",
    "invocation": "/topics",
    "triggers": [],
    "allowed_tools": [],
    "deployments": []
  },
  {
    "id": "Verticals Pipeline",
    "name": "Verticals Pipeline",
    "version": "0.0.0",
    "description": "Produce long form, Peter Attia style vertical-specific content for GoHighLevel affiliate marketing. Series driven, multi language, buyer intent. Ships /for/[vertical]/ hub-and-spoke pages across EN, ES, IN, AR markets. A vertical is any line of business that buys GHL — including marketing agencies, trades (plumbers, HVAC, electricians), and professional services (dentists, chiropractors, med spas).",
    "invocation": "/verticals",
    "triggers": [],
    "allowed_tools": [],
    "deployments": []
  }
];

export const skillsLastGenerated = "2026-04-25T00:05:18.521Z";
