/**
 * Stage 6: Deploy Content
 *
 * Writes article to the city's JSON file, updates Sheet, commits and pushes.
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { updateTodoStatus, logToChangelog } = require('../../lib/sheet');

/**
 * Determine which city file to write to based on the keyword/article.
 * Falls back to a general content file if no city match.
 */
function findTargetCity(article, keyword, constants) {
  const lower = (keyword || '').toLowerCase();

  for (const county of constants.counties) {
    for (const city of county.cities) {
      if (lower.includes(city.name.toLowerCase())) {
        return city;
      }
    }
  }

  // No city match — use the first city in the first county as default
  // (content builder primarily handles city-targeted content)
  return null;
}

/**
 * Deploy an article to the business project.
 */
async function deployArticle(article, todo, config, constants) {
  const keyword = todo.keyword || '';
  const targetCity = findTargetCity(article, keyword, constants);

  if (!targetCity) {
    console.log(`  Deploy: no target city for "${keyword}" — skipping file write`);
    // Still update the TODO status
    if (config.TRACKING_SHEET_ID && todo.row) {
      await updateTodoStatus(config.TRACKING_SHEET_ID, todo.row, 'Done', 'Content created but no target city identified');
    }
    return { deployed: false, reason: 'no target city' };
  }

  const citySlug = targetCity.slug;
  const filePath = path.join(config.LOCAL_NEWS_DIR, `${citySlug}.json`);

  // Read existing articles or start fresh
  let existing = [];
  if (fs.existsSync(filePath)) {
    try {
      existing = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      if (!Array.isArray(existing)) existing = [];
    } catch {
      existing = [];
    }
  }

  // Check for duplicate slug
  if (existing.some(e => e.slug === article.slug)) {
    console.log(`  Deploy: slug "${article.slug}" already exists in ${citySlug}.json — skipping`);
    if (config.TRACKING_SHEET_ID && todo.row) {
      await updateTodoStatus(config.TRACKING_SHEET_ID, todo.row, 'Done', 'Duplicate slug — content already exists');
    }
    return { deployed: false, reason: 'duplicate slug' };
  }

  // Prepend new article
  existing.unshift(article);

  // Ensure directory exists
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  // Write
  fs.writeFileSync(filePath, JSON.stringify(existing, null, 2));
  console.log(`  Deploy: wrote to ${citySlug}.json (${existing.length} total articles)`);

  // Git commit + push
  try {
    execSync(`git add "${filePath}"`, { cwd: config.WEBSITE_PATH, stdio: 'pipe' });
    execSync(
      `git commit -m "Add article: ${article.title.replace(/"/g, '\\"')}\n\nGenerated by content-builder pipeline from SEO gap: ${keyword}"`,
      { cwd: config.WEBSITE_PATH, stdio: 'pipe' }
    );
    execSync('git push', { cwd: config.WEBSITE_PATH, stdio: 'pipe' });
    console.log(`  Deploy: committed and pushed`);
  } catch (err) {
    console.warn(`  Deploy: git push failed — ${err.message}`);
  }

  // Update Sheet
  if (config.TRACKING_SHEET_ID && todo.row) {
    try {
      await updateTodoStatus(
        config.TRACKING_SHEET_ID,
        todo.row,
        'Done',
        `Built: "${article.title}" → ${citySlug}.json`
      );
      await logToChangelog(config.TRACKING_SHEET_ID, {
        page: `/${config.CITY_SLUG_PREFIX}-${citySlug}-${targetCity.state.toLowerCase()}/local-news`,
        action: 'content-built',
        detail: article.title,
        source: 'content-builder',
        category: article.category,
      });
      console.log(`  Deploy: Sheet updated`);
    } catch (err) {
      console.warn(`  Deploy: Sheet update failed — ${err.message}`);
    }
  }

  return { deployed: true, city: targetCity.name, slug: article.slug };
}

module.exports = { deployArticle };
